import { DemoPatient } from '../types.js';

export const DEFAULT_PATIENTS: DemoPatient[] = [
  {
    id: 'alex-mercer',
    name: 'Dhanu',
    dob: '1988-04-12',
    notes: 'Mass-casualty prime demo — conflicting penicillin allergy & active anticoagulant record',
    hash: 'adc3961bae7c654ee37aa2d6aa66f7b7ef7ca88fbaef2293a2fe3018d7cddf47',
    triageLevel: 'CRITICAL RESUSCITATION',
    clinicalProfile: {
      bloodType: 'O Positive (Rh+)',
      allergy: 'Penicillin G / Beta-Lactams (Severe Anaphylaxis)',
      anticoagulant: 'Warfarin Sodium 5mg Daily',
      condition: 'Chronic Nonvalvular Atrial Fibrillation',
      implant: 'St. Jude Accent Dual-Chamber Pacemaker',
      dnrStatus: 'FULL_CODE',
    },
  },
  {
    id: 'elena-rostova',
    name: 'Santhosh',
    dob: '1995-08-23',
    notes: 'Trauma profile — rare AB- blood, severe latex/sulfa allergy, DNR registered',
    hash: '0861f45a956b6b88f0484dc6ad87e4c1519fefc982ced791a6b83f1815cee589',
    triageLevel: 'EMERGENCY TRAUMA BAY 1',
    clinicalProfile: {
      bloodType: 'AB Negative (Rh-)',
      allergy: 'Latex & Sulfonamide Antibiotics (Angioedema)',
      anticoagulant: 'Enoxaparin (Lovenox) 40mg SC Daily',
      condition: 'Acute Deep Vein Thrombosis',
      implant: 'None documented',
      dnrStatus: 'DNR_DO_NOT_RESUSCITATE',
    },
  },
  {
    id: 'marcus-vance',
    name: 'Samual',
    dob: '1972-11-30',
    notes: 'Senior diabetic emergency — Eliquis blood thinner, CAD, pacemaker & titanium hip implant',
    hash: 'cace6d47c95bfc31253da88f34c5cfcadd4bc76648c01b0648146b68647e7534',
    triageLevel: 'CODE RED PRIORITY',
    clinicalProfile: {
      bloodType: 'A Positive (Rh+)',
      allergy: 'Morphine Sulfate (Severe Respiratory Depression)',
      anticoagulant: 'Eliquis (Apixaban) 5mg BID',
      condition: 'Coronary Artery Disease & Type 2 Diabetes',
      implant: 'Total Left Hip Titanium Arthroplasty',
      dnrStatus: 'FULL_CODE',
    },
  },
  {
    id: 'sakthi-demo',
    name: 'Sakthi',
    dob: '1990-03-07',
    notes: 'Cardiac arrest response — B+ blood, Aspirin allergy, active Xarelto therapy',
    hash: '7d2a14f83b5c9e410d83c2f1a0b9e5d84c2f3a1b0e9d5c84b3f2a1e0d9c5b4a3',
    triageLevel: 'CODE RED PRIORITY',
    clinicalProfile: {
      bloodType: 'B Positive (Rh+)',
      allergy: 'Aspirin / NSAIDs (Allergic Bronchospasm)',
      anticoagulant: 'Xarelto (Rivaroxaban) 20mg Daily',
      condition: 'Hypertensive Heart Disease',
      implant: 'None documented',
      dnrStatus: 'FULL_CODE',
    },
  },
  {
    id: 'shiva-demo',
    name: 'Shiva',
    dob: '1983-08-19',
    notes: 'Polytrauma RTA — A- blood, sulfa allergy, active anticoagulation, head injury GCS 8',
    hash: '3c1e89f24a7d6b05e2f90a183d4c7e260b59d3a2c8f10e94b5a72d1c3f08e927',
    triageLevel: 'Level 1 - Resuscitation (Critical)',
    clinicalProfile: {
      bloodType: 'A Negative (Rh-)',
      allergy: 'Sulfonamides (Anaphylaxis)',
      anticoagulant: 'Heparin IV infusion (active)',
      condition: 'Traumatic Brain Injury / Polytrauma',
      implant: 'None documented',
      dnrStatus: 'FULL_CODE',
    },
  },
];
